# Generated by Django 5.0.3 on 2024-03-20 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gametime', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, choices=[(1, 1), (0, 0), (2, 2)], default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (0, 0), (2, 2)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingApp.game')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bettingApp.country')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bettingApp.league'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('league', models.ManyToManyField(to='bettingApp.league')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='awayTeam',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='bettingApp.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='bettingApp.team'),
        ),
    ]
